#language: node_js
#node_js:
#  - 14
#cache: npm
#
#install:
#  - npm install
#
#script:
#  - npm test
#  - npm run-script build
#
#deploy:
#  provider: pages
#  skip_cleanup: true
#  github-token: $GITHUB_TOKEN
#  local_dir: build
#  on:
#    branch: master

language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master