language: node_js
node_js:
  - 14
cache: npm

install:
  - npm install

script:
  - npm test
  - npm build

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
